### ISSUE TITLE
Empty fastq files when demultiplexing multiple tags/samples 

### ISSUE THREAD

**Issue by mcmero** [pachterlab/splitcode#3]
I have four fastq files I'm trying to demultiplex based on two indexes in I1 and R2 but am getting blank fastqs as my output. Here's my summary file:

```
{
        "splitcode_version": "0.28.3",
        "call": "splitcode --config=test.txt --nFastqs=4 --summary=summary.txt --keep=select.txt --no-output test/I1.fastq.gz test/R1.fastq.gz test/R2.fastq.gz test/R3.fastq.gz",
        "barcode_prefix": "",
        "n_fastqs": 4,
        "n_processed": 10000,
        "n_reads_max": 10000,
        "n_assigned": 221,
        "read_length_mean": [8.0, 41.0, 48.0, 41.0],
        "read_length_min": [8, 41, 48, 41],
        "read_length_max": [8, 41, 48, 41],
        "tags_info": {
                "n_tags": 2,
                "n_tag_ids": 2,
                "n_tag_groups": 2
        },
        "general_trimming_info": {
                "trim_5_bases": "",
                "trim_3_bases": "",
                "filter_len": "",
                "n_reads_filtered_out": 0,
                "n_reads_filtered_out_assigned": 0,
                "n_reads_total_trimmed_5": [0, 0, 0, 0],
                "n_reads_total_trimmed_3": [0, 0, 0, 0],
                "n_bases_total_trimmed_5": [0, 0, 0, 0],
                "n_bases_total_trimmed_3": [0, 0, 0, 0],
                "n_reads_total_trimmed_5_assigned": [0, 0, 0, 0],
                "n_reads_total_trimmed_3_assigned": [0, 0, 0, 0],
                "n_bases_total_trimmed_5_assigned": [0, 0, 0, 0],
                "n_bases_total_trimmed_3_assigned": [0, 0, 0, 0],
                "final_read_length_mean_assigned": [8.0, 41.0, 48.0, 41.0],
                "final_read_length_min_assigned": [8, 41, 48, 41],
                "final_read_length_max_assigned": [8, 41, 48, 41]
        },
        "quality_trimming_info": {
                "quality_trim_5": 0,
                "quality_trim_3": 0,
                "quality_trim_pre": 0,
                "quality_trim_naive": 0,
                "quality_trim_threshold": -1,
                "quality_phred64": 0,
                "n_reads_quality_trimmed_5": [0, 0, 0, 0],
                "n_reads_quality_trimmed_3": [0, 0, 0, 0],
                "n_bases_quality_trimmed_5": [0, 0, 0, 0],
                "n_bases_quality_trimmed_3": [0, 0, 0, 0],
                "n_reads_quality_trimmed_5_assigned": [0, 0, 0, 0],
                "n_reads_quality_trimmed_3_assigned": [0, 0, 0, 0],
                "n_bases_quality_trimmed_5_assigned": [0, 0, 0, 0],
                "n_bases_quality_trimmed_3_assigned": [0, 0, 0, 0]
        },
        "tag_trimming_info": [
        ],
        "extraction_info": [
        ],
        "developer_use_info": {
                "tags_vector_size": 2,
                "tags_map_size": 2,
                "num_elements_in_tags_map": 2,
                "assign_id_map_size": 0,
                "sub_assign_id_map_size": 0,
                "always_assign": 1
        }
}
```

Here's my config file:
```
groups  ids     tags    locations       minFinds        maxFinds        next
i7      I7_013  TAAGGCGA        0:0:8   1       1       {{i5}}
i5      I5_003  GCGATCTA        2:29:37 1       1       -
```

and select file:
```
I7_013,I5_003 G321_b5_sample1_1_1_H3K27me3_AB
```

I noticed that when I specify the flags `--output=out1.fq,out2.fq,out3.fq --select=1,2,3` I can get splitcode to output reads for this one sample. When I add all the other samples however, I get blank fastq outputs. Any suggestions on troubleshooting, and is there a more verbose/debugging level output?

**Comment by Yenaled** [comment]
Hello! Thanks for your question! minFinds should be minFindsG and maxFinds should be maxFindsG.

The reason for this is that i7 and i5 are the "groups" so we want to find ANY i7 and i5 index exactly one time.

If we specified minFinds (rather than minFindsG) for each row of the config file (i.e. for each individual index sequence), that would mean that that particular index sequence must be found at least one time. So if you have an i7 index of TAAGGCGA and another i7 index of AGGGGCGT, and you set minFinds=1 for both of those, that means that you're only keeping reads where TAAGGCGA is found at least once AND where AGGGGCGT is found at least once (i.e. a single line of reads must contain both TAAGGCGA and AGGGGCGT, otherwise it's discarded).

**Comment by mcmero** [comment]
Thanks for the explanation, it's now working with minFindsG and maxFindsG and the following parameters:

```
splitcode \
    --config=config.txt \
    --nFastqs=4 \
    --summary=summary.txt \
    --keep=select.txt \
    --gzip \
    --unassigned=unmapped_R1.fastq.gz,unmapped_R2.fastq.gz,unmapped_R3.fastq.gz \
    --output=R1_out.fastq.gz,R2_out.fastq.gz,R3_out.fastq.gz \
    --select=1,2,3 \
    test/I1.fastq.gz \
    test/R1.fastq.gz \
    test/R2.fastq.gz \
    test/R3.fastq.gz
```
I'm still a little bit confused about the output parameters. The documentation suggests that the demultiplexed files should still be output with the`--no-output` parameter flag, but when I substitute the flag for `--output=<files>` my fastq files are created but have no reads. If I use the output flag as above, my `_out.fastq.gz` files are blank but demultiplexed files are correctly generated.

**Comment by Yenaled** [comment]
Yes, that's because all the stuff in --output= is directed into the demultiplexed files so the files created via --output will not have anything. If you have a row in --keep that lacks the second column, that combination of tags will be directed to the files in --output (in that case, the --output files will be nonempty).
